# Chatterbot

In [ ]:
!pip install chatterbot

     |████████████████████████████████| 71kB 2.4MB/s 


In [ ]:
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

In [ ]:
chatbot = ChatBot('Testing bot')
trainer = ListTrainer(chatbot, show_training_progress=True)

trainer.train([
    "Hi, can I help you?",
    "Sure, I'd like to book a flight to Iceland.",
    "Your flight has been booked."
])

# Get a response to the input text 'I would like to book a flight.'
response = chatbot.get_response('I would like to book a flight.')

print(response)

List Trainer: [####################] 100%
Hi, can I help you?


# suriyadeepan practical_seq2seq

In [ ]:
!git clone https://github.com/suriyadeepan/practical_seq2seq.git


Cloning into 'practical_seq2seq'...
remote: Enumerating objects: 167, done.
remote: Total 167 (delta 0), reused 0 (delta 0), pack-reused 167
Receiving objects: 100% (167/167), 7.13 MiB | 5.71 MiB/s, done.
Resolving deltas: 100% (73/73), done.


In [ ]:
cd practical_seq2seq

/content/practical_seq2seq


In [ ]:
!pip install tensorflow==1.0.0

     |████████████████████████████████| 44.5MB 65kB/s 
  Found existing installation: tensorflow 2.3.0
    Uninstalling tensorflow-2.3.0:
      Successfully uninstalled tensorflow-2.3.0


In [ ]:
import tensorflow as tf
import numpy as np

# preprocessed data
from datasets.twitter import data
import data_utils

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:472: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:473: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:474: FutureWarning: Passing (type, 1) or 

In [ ]:
!python /content/practical_seq2seq/datasets/twitter/data.py


>> Read lines from file

:: Sample from read(p) lines
[]

>> Filter lines
[]

>> 2nd layer of filtering
10% filtered from original data

q : hola como estas ; a : yo bien y t

q : tambin estoy bien es un hermoso da ; a : lo es este da soleado me encanta

>> Segment lines into words

:: Sample from segmented list of words

q : ['hola', 'como', 'estas'] ; a : ['yo', 'bien', 'y', 't']

q : ['tambin', 'estoy', 'bien', 'es', 'un', 'hermoso', 'da'] ; a : ['lo', 'es', 'este', 'da', 'soleado', 'me', 'encanta']

 >> Index words

 >> Zero Padding

 >> Save numpy arrays to disk


In [ ]:
# load data from pickle and npy files
metadata, idx_q, idx_a = data.load_data(PATH='/content/practical_seq2seq/datasets/twitter/')
(trainX, trainY), (testX, testY), (validX, validY) = data_utils.split_dataset(idx_q, idx_a)
print(trainX)
# parameters 
xseq_len = trainX.shape[-1]
yseq_len = trainY.shape[-1]
batch_size = 1
xvocab_size = len(metadata['idx2w'])  
yvocab_size = xvocab_size
emb_dim = 1024

import seq2seq_wrapper

# In[7]:

model = seq2seq_wrapper.Seq2Seq(xseq_len=xseq_len,
                               yseq_len=yseq_len,
                               xvocab_size=xvocab_size,
                               yvocab_size=yvocab_size,
                               ckpt_path='ckpt/twitter/',
                               emb_dim=emb_dim,
                               num_layers=3,
                               epochs=10
                               )


# In[8]:

val_batch_gen = data_utils.rand_batch_gen(validX, validY, 32)
train_batch_gen = data_utils.rand_batch_gen(trainX, trainY, batch_size)

# In[9]:
sess = model.restore_last_session()
sess = model.train(train_batch_gen, val_batch_gen)

[[19 20 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [22 23 10  7  8 24  4  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 5 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [26 27 28 29  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [30 31  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [32  2 33 34 11 35  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
<log> Building Graph </log>
<log> Training started </log>
0


ValueError: ignored

# Marsan-Ma-zz / tf_chatbot_seq2seq_antilm 

In [ ]:
!git clone https://github.com/Marsan-Ma-zz/tf_chatbot_seq2seq_antilm.git

Cloning into 'tf_chatbot_seq2seq_antilm'...
remote: Enumerating objects: 214, done.
remote: Total 214 (delta 0), reused 0 (delta 0), pack-reused 214
Receiving objects: 100% (214/214), 11.17 MiB | 7.54 MiB/s, done.
Resolving deltas: 100% (121/121), done.


In [ ]:
pip install tensorflow==1.0.0 jieba

In [ ]:
cd tf_chatbot_seq2seq_antilm

/content/tf_chatbot_seq2seq_antilm


In [ ]:
!ls

practical_seq2seq  sample_data	tf_chatbot_seq2seq_antilm


In [ ]:
!python3 /content/tf_chatbot_seq2seq_antilm/main.py --mode train --model_name lyrics_ptt --steps_per_checkpoint 1 --batch_size=2

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:472: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:473: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:474: FutureWarning: Passing (type, 1) or 

# AbrahamSanders seq2seq-chatbot.git

In [ ]:
!git clone https://github.com/AbrahamSanders/seq2seq-chatbot.git

Cloning into 'seq2seq-chatbot'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 319 (delta 0), reused 0 (delta 0), pack-reused 316
Receiving objects: 100% (319/319), 19.19 MiB | 28.69 MiB/s, done.
Resolving deltas: 100% (146/146), done.


In [ ]:
!pip install jsonpickle
!pip install --upgrade tensorflow-gpu==1.*

     |████████████████████████████████| 411.0MB 40kB/s 


In [ ]:
cd seq2seq-chatbot

/content/seq2seq-chatbot/seq2seq-chatbot


In [ ]:
ls

doc_files/  LICENSE  README.md  seq2seq-chatbot/


In [ ]:
!python /content/seq2seq-chatbot/seq2seq-chatbot/train.py --datasetdir=./datasets/csv


Reading dataset 'csv'...

Final shared vocab size: 67

Splitting 16 samples into training & validation sets (0.0% used for validation)...
Training set: 16 samples. Validation set: 0 samples.
Sorting training & validation sets to increase training efficiency...
Initializing model...

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.





Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
Instructions for updating:
Please use `keras.layers.Bidirectional(keras.layers.RNN

# jackfrost1411 naive_bayes_chatbot


In [ ]:
! git clone https://github.com/jackfrost1411/naive_bayes_chatbot.git

Cloning into 'naive_bayes_chatbot'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 19 (delta 6), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (19/19), done.


In [ ]:
cd naive_bayes_chatbot

/content/naive_bayes_chatbot


In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
labels = []
questions = []
for line in open('que.txt', encoding="utf8"):
    labels.append(line.strip().split(" ")[-1])
    questions.append(" ".join(line.strip().split(" ")[:-1]))
answers = []
for line in open('ans.txt', encoding="utf8"):
    answers.append(line.strip())

In [ ]:
bow_vectorizer = CountVectorizer()
training_vectors = bow_vectorizer.fit_transform(questions)
classifier = MultinomialNB()
classifier.fit(training_vectors, labels)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
class ChatBot:
  exit_commands = ("quit", "pause", "exit", "goodbye", "bye", "later", "stop")
  def start_chat(self):
    user_response = input("Hi, I'm a chatbot trained on random dialogs!!\n")
    self.chat(user_response)
  
  def chat(self, reply):
    while not self.make_exit(reply):
      reply = input(self.generate_response(reply)+"\n")
    return
  
  def generate_response(self, sentence):
    input_vector = bow_vectorizer.transform([sentence])
    predict = classifier.predict(input_vector)
    index = int(predict[0])
    print("Accurate:",str(classifier.predict_proba(input_vector)[0][index-1] * 100)[:5] + "%")
    return answers[index-1]
  
  def make_exit(self, reply):
    for exit_command in self.exit_commands:
      if exit_command in reply:
        print("Ok, have a great day!")
        return True
    return False

In [ ]:
etcetera = ChatBot()
etcetera.start_chat()

Hi, I'm a chatbot trained on random dialogs!!
hello
Accurate: 10.64%
Hi there, how are you !?
good. You?
Accurate: 4.914%
My name is etcetera, but you can call me etc.
Hello etc
Accurate: 10.64%
Hi there, how are you !?
good
Accurate: 6.338%
Good night! Sweet dreams :)
thanks
Accurate: 6.512%
Good, tell me..
tell you what?
Accurate: 3.431%
I'm 22 years old
i'm 23
Accurate: 8.108%


KeyboardInterrupt: ignored

# AbdelrahmanRadwan Open-Domain-ChatBot

In [1]:
!git clone https://github.com/AbdelrahmanRadwan/Open-Domain-ChatBot.git

Cloning into 'Open-Domain-ChatBot'...
remote: Enumerating objects: 262, done.
remote: Total 262 (delta 0), reused 0 (delta 0), pack-reused 262
Receiving objects: 100% (262/262), 58.22 MiB | 10.10 MiB/s, done.
Resolving deltas: 100% (58/58), done.


In [2]:
cd Open-Domain-ChatBot

/content/Open-Domain-ChatBot


In [3]:
!pip install -r requirements.txt

     |████████████████████████████████| 320.4MB 49kB/s 


In [5]:
!python3 -m nltk.downloader punkt

/usr/lib/python3.6/runpy.py:125: RuntimeWarning: 'nltk.downloader' found in sys.modules after import of package 'nltk', but prior to execution of 'nltk.downloader'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [6]:
!python3 main.py --verbose --corpus lightweight --datasetTag ./data/lightweight/text.txt

2020-10-15 21:57:23.580790: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    from chatbot import chatbot
  File "/content/Open-Domain-ChatBot/chatbot/chatbot.py", line 33, in <module>
    from chatbot.textdata import TextData
  File "/content/Open-Domain-ChatBot/chatbot/textdata.py", line 30, in <module>
    from chatbot.corpus.cornelldata import CornellData
ModuleNotFoundError: No module named 'chatbot.corpus'
